import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClientProvider } from "@/provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Manoharpura Mokshdham Vikas Samiti",
  // description: "Generated by create next app",
  description:
    "Manoharpura Mokshdham Vikas Samiti is a community-driven NGO dedicated to organizing welfare activities like blood donation camps and supporting local development through its dedicated committee.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
